### ISSUE TITLE
run once

### ISSUE THREAD

**Issue by hvhol** [jjtbsomhorst/homeyrss#1]
Hi,
The app in a flow run once , with a rss feed from nu.nl then for the second time its not working !

**Comment by jjtbsomhorst** [comment]
Which version of the app are you using ? The current version in the app store? Or the github version?

**Comment by hvhol** [comment]
The github version

**Comment by jjtbsomhorst** [comment]
Can you tell me which settings you are using? Maybe provide a screenshot of the settings so I can reproduce it?

**Comment by hvhol** [comment]
![rsshomey](https://cloud.githubusercontent.com/assets/25131976/21962000/2f134f00-db19-11e6-81a3-19363c9c47fc.JPG)
with this rss feed:
http://www.nu.nl/rss/Algemeen

**Comment by jjtbsomhorst** [comment]
Thanks for reporting this issue. I have updated the repository with a fix for this. Could you install this new version on your homey and verify that it has been fixed?

**Comment by hvhol** [comment]
Hi its working very very well now , thank you very much this is a very nice app How can I donate ?

**Comment by jjtbsomhorst** [comment]
Great. Thank you for reporting the bug / issue. You can donate using the Paypal button in the decription/readme.

**Comment by hvhol** [comment]
Hi ,
![appcrash](https://cloud.githubusercontent.com/assets/25131976/21962346/e04bf7e0-db23-11e6-85dc-52066aecd971.JPG)
The App is gecrashed , I dont no why !
