### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by hvhol** [jjtbsomhorst/homeyrss#2]
Hi,
The app crashed after somewhile (Version 1.01)
![appcrash](https://cloud.githubusercontent.com/assets/25131976/21962352/1b02baae-db24-11e6-890a-06776ac9fd56.JPG)

I have made a flow with:
http://projects.knmi.nl/RSSread/rss_KNMIverwachtingen.php
and 
http://projects.knmi.nl/RSSread/rss_KNMIwaarschuwingen.php
then it crashed

info:
TypeError: this.parser.done is not a function
at flowProcessor.onFeedParsed (/libs/flowProcessor.js:35:39)
at emitNone (events.js:72:20)
at emit (events.js:166:7)
at SAXStream.wrapper.__wrappers.(anonymous function) (/node_modules/feedme/node_modules/eventyoshi/lib/index.js:135:12)
at emitNone (events.js:67:13)
at SAXStream.emit (events.js:166:7)
at Object.SAXStream._parser.onend (/node_modules/feedme/node_modules/sax/lib/sax.js:190:10)
at emit (/node_modules/feedme/node_modules/sax/lib/sax.js:640:35)
at end (/node_modules/feedme/node_modules/sax/lib/sax.js:683:5)
at Object.SAXParser.end (/node_modules/feedme/node_modules/sax/lib/sax.js:154:24)

Exit code: 1
Exit signal: null

Grtz Henk

**Comment by jjtbsomhorst** [comment]
Thanks for the crash report. I have updated the github repo. Could you please test it again? 👍

**Comment by hvhol** [comment]
Hi It works like a zonnetje ;-)

 

Thnx

 

Van: JJTB Somhorst [mailto:notifications@github.com] 
Verzonden: zondag 15 januari 2017 13:47
Aan: jjtbsomhorst/homeyrss <homeyrss@noreply.github.com>
CC: hvhol <hvhol@me.com>; Author <author@noreply.github.com>
Onderwerp: Re: [jjtbsomhorst/homeyrss] App Crashed (#2)

 

Thanks for the crash report. I have updated the github repo. Could you please test it again? 👍

**Comment by jjtbsomhorst** [comment]
I just updated the repo again with a new feature. If you want could you test it once again?

**Comment by hvhol** [comment]
Yes ofcourse what is the new feature ?

 

Van: JJTB Somhorst [mailto:notifications@github.com] 
Verzonden: zondag 15 januari 2017 15:29
Aan: jjtbsomhorst/homeyrss <homeyrss@noreply.github.com>
CC: hvhol <hvhol@me.com>; Author <author@noreply.github.com>
Onderwerp: Re: [jjtbsomhorst/homeyrss] App Crashed (#2)

 

I just updated the repo again with a new feature. If you want could you test it once again?

**Comment by jjtbsomhorst** [comment]
You can now add a new card to the action column. It allowes to specificy an index of a item in de feed. For instance with the KNMI feed you can now say you want to hear the second or thirth item only. Be aware that the index is 0 based. (so the first item would be 0 instead of 1).

**Comment by hvhol** [comment]
Works good!!!

Verstuurd vanaf mijn iPhone
